version: '3'
services:
  riding-tracer:
    container_name: riding-tracer
    image: node:18.19-alpine
    volumes:
      - /opt/riding-tracer:/opt/riding-tracer
    environment:
      APP_KEY: ''
      APP_SECRET: ''
      PORT: 5173
      DATABASE_URL: 'file:/opt/riding-tracer/app.db'
      SESSION_SECRET: 'RIDING-TRACER'
    ports:
      - target: 5173
        published: 5173
    working_dir: /opt/riding-tracer
    command: sh -c "npm config set registry https://registry.npmmirror.com && npm install && npx prisma generate && npx remix-serve build/server/index.js"